version: "3.0"
services:
  nginx:
    container_name: nginx
    build: 
      context: ""
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/sites-available/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - 80:80
    networks: 
      - logging-network
  elk:
    container_name: elk
    image: 682115170512.dkr.ecr.us-east-1.amazonaws.com/elk:8.6.2
    build: 
      context: ""
      dockerfile: ./Dockerfile
    ports:
      - 9200:9200
      - 5601:5601
      - 5044:5044
    networks: 
      - logging-network
    volumes:
      - ./elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elk/logstash:/etc/logstash
      - ./elk/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./elk/data:/usr/share/elasticsearch/data
      - ./elk/logs:/usr/share/elasticsearch/logs
networks: 
  logging-network:
    driver: bridge
volumes:
  elk:
  nginx:  

